### ISSUE TITLE
May not work with non-standard rails structures

### ISSUE THREAD

**Issue by blakewest** [NathanielWroblewski/schemapper#2]
I installed this, and ran it. All I got was a completely blank HTML file. And the d3.min.js file was also blank. Not sure what root cause is here, but in case it helps, the structure of our rails project is a bit non-standard and it more component based. It looks something like this...

-apps
  -app1
    -app
      -models
      -views
      -controllers
  -app2
    -app
      -models
      -views, etc.
-config
-lib
-plugins 
  -plugin1 (this contains the actual models we use) 
  -plugin2

**Comment by NathanielWroblewski** [comment]
Providing your Rails application responds properly to `Rails.application.eager_load!` then `ActiveRecord::Base.descendants`, etc. should work.  It's difficult for me to replicate this sort of environment, but the code that executes is relatively short.

I would recommend first starting a `rails console`, and just going line-by-line through the following:

```
Rails.application.eager_load!
models = ActiveRecord::Base.descendants
tables = models.map(&:table_name)
```

If that works, then it may be a pathing issue caused by non-standard placement of your Rails `config/environment.rb`.

This gem is actually pretty small, and thus, easy to troubleshoot.  I'll update the readme with a better description, and hopefully that will help you.

**Comment by NathanielWroblewski** [comment]
I've added [some documentation](https://github.com/NathanielWroblewski/schemapper/blob/master/README.md#explanation-of-code) to help you debug further.  Let me know if you have any other questions.
